version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    container_name: shareit_gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit_server_image
    container_name: shareit_server_container
    ports:
      - "9090:9090"
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    container_name:
      "shareit_db_container"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=user_shareit
      - POSTGRES_PASSWORD=password