version: '3.8'

services:

  gateway:

    build: .
    image: gateway_image
    container_name: shareit_gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:

    build: .
    image: server_image
    container_name: shareit_server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
        - DB_NAME=shareit
        - POSTGRES_USER=user_shareit
        - POSTGRES_PASSWORD=password
        - DB_HOST=db
        - DB_PORT=5432

  db:
    image: postgres:16.1-alpine
    container_name:
      "shareit_db_container"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=user_shareit
      - POSTGRES_PASSWORD=password